### ISSUE TITLE
[EXT] - Interfaz de Varias preguntas en la misma votación

### ISSUE THREAD

**Issue by joancafom** [joancafom/decide-ganimedes-visualizacion#10]
_[Incidencia replicada del repositorio Decide-Ganímedes](https://github.com/decide-ganimedes/decide-ganimedes/issues/18)_

Implementar una interfaz de votación que permita incluir varias preguntas en una votación.

__Rama:__ responsive

**Comment by josembell** [comment]
**Encargado:** @josembell

**Comment by josembell** [comment]
**Verificador:** @aliviaord
