### ISSUE TITLE
Desarrollar fichero CSS padre

### ISSUE THREAD

**Issue by josembell** [joancafom/decide-ganimedes-visualizacion#12]
**Descripción:** Se deberá desarrollar un fichero CSS que contenga los elementos principales para cada vista del módulo de visualización (fuente predeterminada, color de fuente, color de fondo... etc) y que sirva como heredero a los demás ficheros CSS hijos.

**Rama**: responsive

**Comment by josembell** [comment]
**Encargado:** @josembell

**Comment by josembell** [comment]
**Verificador:** @joancafom

**Comment by joancafom** [comment]
__[Reprobada]__

- La plantilla base debería presentar [elementos que posibiliten la herencia](https://docs.djangoproject.com/en/1.7/topics/templates/#id1) (bloques de Django).
- La localización de los ficheros no es la correcta. Los archivos base deben pertenecer a la subcarpeta "base" del proyecto.
- Los archivos de tipo .CSS, .JS e imágenes deberán estar ubicados en la ruta de ficheros estáticos de Django.
- Importación incorrecta del framework _Materialize_ . El fichero .js existe en el directorio, pero no se usa en la plantilla base.
- El título de la plantilla base común no debería ser "Visualización".
