### ISSUE TITLE
Desarrollar fichero CSS para ended.html

### ISSUE THREAD

**Issue by josembell** [joancafom/decide-ganimedes-visualizacion#13]
**Descripción:** Se deberá desarrollar un fichero CSS para la plantilla de ended.html con cambios significativos específicos para dicha plantilla. Debe de heredar de el fichero CSS padre.

**Rama:** responsive

**Comment by josembell** [comment]
**Encargado:** @Reloxed

**Comment by Reloxed** [comment]
**Verificador:** @josembell

**Comment by josembell** [comment]
**[Reprobada]:** El estilo definido no cumple con las normas establecidas. Se debe de hacer uso de tarjetas de materializeCSS para mostrar información usando los colores predeterminados, así como las tags de html y las fuentes. Más info [aquí](https://github.com/joancafom/decide-ganimedes-visualizacion/issues/7).
