### ISSUE TITLE
Aplicar estilo CSS a las plantillas de los resultados que se exportan

### ISSUE THREAD

**Issue by aliviaord** [joancafom/decide-ganimedes-visualizacion#16]
__Descripción:__ Se deberá desarrollar un fichero CSS para cada plantilla que se use en la generación de los archivos .pdf y .png con los cambios pertinentes para su correcta visualización. Se incluyen tanto la plantilla para resultados de votaciones en curso como para resultados de votaciones finalizadas. Debe heredar del fichero CSS padre.

__Rama:__ responsive

**Comment by josembell** [comment]
**Encargado:** @aliviaord

**Comment by josembell** [comment]
**[WontFix]** Incompatibilidad del export pdf utilizado con CSS.
