### ISSUE TITLE
Implementación de una caché para las estadísticas

### ISSUE THREAD

**Issue by joancafom** [joancafom/decide-ganimedes-visualizacion#21]
__Descripción:__ Debido al posible alto coste de cómputo de las estadísticas y la alta concurrencia de acceso a las mismas, se propone implementar un sistema de caché que las mantenga en memoria durante un tiempo determinado. 

__Rama:__ estadisticas

**Comment by joancafom** [comment]
__Encagado:__ @joancafom

**Comment by joancafom** [comment]
__Verificador:__ @aliviaord

**Comment by aliviaord** [comment]
__[Reprobada]__ Excepción de carácter grave al intentar acceder a las estadísticas en caché de una votación en curso. La ejecución del programa se ve interrumpida por un _desbordamiento de búffer_ provocado por superar el número de llamadas recursivas permitidas.

Para más detalles, acceder a la incidencia #42 donde se explica el problema.
