### ISSUE TITLE
Estilado de las estadísticas en tiempo de votación

### ISSUE THREAD

**Issue by joancafom** [joancafom/decide-ganimedes-visualizacion#22]
__Descripción:__ Se deberá desarrollar un fichero CSS para la plantilla ongoing.html, que muestra las estadísticas de las votaciones en curso. Deberá mantener el estilo general de la aplicación, heredando muy posiblemente del fichero CSS base. 

__Rama:__ responsive

**Comment by josembell** [comment]
**Encargado:** @joancafom
