### ISSUE TITLE
Mostrar estadísticas en las votaciones finalizadas

### ISSUE THREAD

**Issue by aliviaord** [joancafom/decide-ganimedes-visualizacion#43]
__Descripción:__ El sistema deberá permitir la visualización en las votaciones finalizadas de estadísticas básicas (tamaño del censo, personas que han votado y el porcentaje de participación), así como estadísticas avanzadas:
- Análisis de la composición del voto según rango etario (por ejemplo, el % de personas de 18 a 25 que han participado respecto al total)
- Análisis de la edad media de las personas que han votado
- Análisis de la edad media de las personas que no han votado
- Número de hombres que han participado en la votación
- Número de personas de género no binario que han participado en la votación
- Porcentaje de participación de mujeres respecto a su total
- Porcentaje de participación de hombres respecto a su total
- Porcentaje de participación de personas de género no binario respecto a su total

__Rama:__ estadisticas

**Comment by joancafom** [comment]
__Encargado:__ @Reloxed

**Comment by joancafom** [comment]
__[Wontfix]:__ Falta de tiempo para su implementación por parte del encargado. Se ha acordado descartar los cambios relacionados con esta incidencia.
