### ISSUE TITLE
Adaptar las estadísticas a los cambios de los demás módulos

### ISSUE THREAD

**Issue by aliviaord** [joancafom/decide-ganimedes-visualizacion#45]
__Descripción:__ Adaptar los cálculos de las estadísticas a los nuevos cambios provenientes de los demás módulos o subsistemas. Tanto las estadísticas básicas (tamaño del censo, personas que han votado y el porcentaje de participación), como las estadísticas avanzadas:
- Análisis de la composición del voto según rango etario (por ejemplo, el % de personas de 18 a 25 que han participado respecto al total)
- Análisis de la edad media de las personas que han votado
- Análisis de la edad media de las personas que no han votado
- Número de hombres que han participado en la votación
- Número de personas de género no binario que han participado en la votación
- Porcentaje de participación de mujeres respecto a su total
- Porcentaje de participación de hombres respecto a su total
- Porcentaje de participación de personas de género no binario respecto a su total

__Rama:__ estadisticas

**Comment by joancafom** [comment]
__Encargado:__ @joancafom

**Comment by joancafom** [comment]
__Verificador:__ @josembell
