### ISSUE TITLE
[EXT] - Diseño único

### ISSUE THREAD

**Issue by joancafom** [joancafom/decide-ganimedes-visualizacion#7]
_[Incidencia replicada del repositorio Decide-Ganímedes](https://github.com/decide-ganimedes/decide-ganimedes/issues/7)_

Utilizar un estilo de diseño único entre todos los módulos de la aplicación Decide para aportar una vista de aplicación uniforme. Para conseguir esto, podemos considerar lo siguiente:

- Utilizar un framework de diseño para sitios web como Bootstrap, Material Design...
- Crear una ruta/carpeta única para todos los módulos (grupos de decide) en los que estén los parámetros del diseño. Por ejemplo, podríamos crear una carpeta padre que se llame 'design' y dentro de esa carpeta crear una carpeta general para parametros de diseño generales y una carpeta por cada modulo para paginas únicas.

__Rama:__ responsive

**Comment by josembell** [comment]
**Encargado:** @josembell

**Comment by josembell** [comment]
## Decide Ganímedes
### Plantilla de diseño

- Se desarrollará el diseño y vistas de la plataforma Decide Ganímedes mediante el framework [MaterializeCSS](https://materializecss.com).

- El color por defecto de la plataforma Ganímedes será blue-grey darken-2 (#455a64), siguiendo la paleta de colores establecida por el framework. 

- Los colores de realce, y que deben de utilizarse únicamente para destacar elementos (como botones, tarjetas, inputs...) serán, por orden de preferencia: teal (#009688), teal lighten-1 (#26a69a) y  teal lighten-2 (#4db6ac). Estos colores nunca deben utilizarse el textos, a menos que sean enlaces.

- El color utilizado para el fondo de la plataforma será grey lighten-5 (#fafafa).

- Cada vista contendrá un menú navbar del tipo nav-wrapper, con el logotipo centrado (brand-logo center) y con el color predeterminado (blue-grey darken-2). Este menú podrá contener enlaces y botones especiales a la derecha si se considera necesario.

- Las fuentes predeterminadas de la plataforma serán Roboto (para textos) y Roboto Slab (para títulos y textos descatables). El color predeterminado para ambas fuentes será blue-grey darken-4 (#263238) siempre y cuando el fondo sea blanco o un tono claro. De lo contrario, se utilizará el color white (#ffffff) para facilitar la lectura del texto.

- Los títulos de cada vista deberán ir en Roboto Slab, en color blue-grey darken-4 y con la etiqueta **h4**.

- Los subtítulos de cada vista deberán ir en Roboto, en color blue-grey darken-4 y con la etiqueta **h5**.

- El texto por defecto deberá ir en Roboto, en color blue-grey darken-4.

- El logotipo del banner deberá ir en Roboto Slab en color white, mientras que el resto de botones y textos del banner deberá ir en Roboto. Se podrá hacer uso de [iconos de google](https://materializecss.com/icons.html) en el menú.

- Para resaltar información, se hará uso de las tarjetas o cards de materialize. Estas deberán de llevar los colores de realce definidos anteriormente. Pueden utilizar distintos tonos de realce para distinguir las tarjetas.

- Se debe de definir un margen tanto por la izquierda como por la derecha del cuerpo, con un valor de 30px para cada margen.

- Se deberá de definir un margen que separe el menú del cuerpo (margin-bottom) con un valor de 50px.

- Se podrá hacer uso de [iconos de google](https://materializecss.com/icons.html) en cualquier parte de la web siempre y cuando el icono aporte información relevante al contenido.

**Comment by josembell** [comment]
**Verificador:** @joancafom
