### ISSUE TITLE
[EXT] - Traducir la interfaz a otros idiomas

### ISSUE THREAD

**Issue by joancafom** [joancafom/decide-ganimedes-visualizacion#8]
_[Incidencia replicada del repositorio Decide-Ganímedes](https://github.com/decide-ganimedes/decide-ganimedes/issues/8)_

Internacionalizar el sistema de forma que esté disponible en español, inglés y catalán.

__Rama:__ traduccion

**Comment by Reloxed** [comment]
**Encargado:** @Reloxed

**Comment by joancafom** [comment]
Reabierta tras cierre automático erróneo debido a referencias cruzadas con el repo común.
